services:
  - type: web
    name: minecraft-afk-bot-dashboard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
